
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OBJDICTMASTER_H
#define OBJDICTMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDictMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * ObjDictMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ObjDictMaster_Data;
extern UNS8 IAP_IAP_SEG[256];		/* Mapped at index 0x5FFF, subindex 0x01 */
extern UNS64 IAP_IAP_CMD;		/* Mapped at index 0x5FFF, subindex 0x02 */
extern UNS64 IAP_IAP_CMD_R;		/* Mapped at index 0x5FFF, subindex 0x03 */
extern UNS32 IAP_SOFT_VERSION;		/* Mapped at index 0x5FFF, subindex 0x04 */

#endif // OBJDICTMASTER_H
