
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDictMaster.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 IAP_IAP_SEG[256] = "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";		/* Mapped at index 0x5FFF, subindex 0x01 */
UNS64 IAP_IAP_CMD = 0x0;		/* Mapped at index 0x5FFF, subindex 0x02 */
UNS64 IAP_IAP_CMD_R = 0x0;		/* Mapped at index 0x5FFF, subindex 0x03 */
UNS32 IAP_SOFT_VERSION = 0x13161116;		/* Mapped at index 0x5FFF, subindex 0x04 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDictMaster_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDictMaster_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDictMaster_iam_a_slave = 0;

TIMER_HANDLE ObjDictMaster_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDictMaster_obj1000 = 0x0;	/* 0 */
                    subindex ObjDictMaster_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDictMaster_obj1001 = 0x0;	/* 0 */
                    subindex ObjDictMaster_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDictMaster_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDictMaster_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex ObjDictMaster_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 ObjDictMaster_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 ObjDictMaster_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 ObjDictMaster_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 ObjDictMaster_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDictMaster_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex ObjDictMaster_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ObjDictMaster_obj1017 = 0x0;	/* 0 */
                    ODCallback_t ObjDictMaster_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDictMaster_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDictMaster_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 ObjDictMaster_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 ObjDictMaster_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 ObjDictMaster_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex ObjDictMaster_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 ObjDictMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex ObjDictMaster_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 ObjDictMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 ObjDictMaster_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex ObjDictMaster_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDictMaster_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 ObjDictMaster_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDictMaster_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDictMaster_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDictMaster_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDictMaster_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDictMaster_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDictMaster_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDictMaster_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDictMaster_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDictMaster_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDictMaster_obj1400_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDictMaster_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 ObjDictMaster_obj1600[] = 
                    {
                      0x5FFF0240	/* 1610547776 */
                    };
                    subindex ObjDictMaster_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDictMaster_obj1600[0] }
                     };

/* index 0x5FFF :   Mapped variable IAP */
                    UNS8 ObjDictMaster_highestSubIndex_obj5FFF = 4; /* number of subindex - 1*/
                    ODCallback_t IAP_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDictMaster_Index5FFF[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDictMaster_highestSubIndex_obj5FFF },
                       { RW, domain, 256, (void*)&IAP_IAP_SEG },
                       { RW, uint64, sizeof (UNS64), (void*)&IAP_IAP_CMD },
                       { RW, uint64, sizeof (UNS64), (void*)&IAP_IAP_CMD_R },
                       { RW, uint32, sizeof (UNS32), (void*)&IAP_SOFT_VERSION }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable ObjDictMaster_objdict[] = 
{
  { (subindex*)ObjDictMaster_Index1000,sizeof(ObjDictMaster_Index1000)/sizeof(ObjDictMaster_Index1000[0]), 0x1000},
  { (subindex*)ObjDictMaster_Index1001,sizeof(ObjDictMaster_Index1001)/sizeof(ObjDictMaster_Index1001[0]), 0x1001},
  { (subindex*)ObjDictMaster_Index1016,sizeof(ObjDictMaster_Index1016)/sizeof(ObjDictMaster_Index1016[0]), 0x1016},
  { (subindex*)ObjDictMaster_Index1017,sizeof(ObjDictMaster_Index1017)/sizeof(ObjDictMaster_Index1017[0]), 0x1017},
  { (subindex*)ObjDictMaster_Index1018,sizeof(ObjDictMaster_Index1018)/sizeof(ObjDictMaster_Index1018[0]), 0x1018},
  { (subindex*)ObjDictMaster_Index1200,sizeof(ObjDictMaster_Index1200)/sizeof(ObjDictMaster_Index1200[0]), 0x1200},
  { (subindex*)ObjDictMaster_Index1280,sizeof(ObjDictMaster_Index1280)/sizeof(ObjDictMaster_Index1280[0]), 0x1280},
  { (subindex*)ObjDictMaster_Index1400,sizeof(ObjDictMaster_Index1400)/sizeof(ObjDictMaster_Index1400[0]), 0x1400},
  { (subindex*)ObjDictMaster_Index1600,sizeof(ObjDictMaster_Index1600)/sizeof(ObjDictMaster_Index1600[0]), 0x1600},
  { (subindex*)ObjDictMaster_Index5FFF,sizeof(ObjDictMaster_Index5FFF)/sizeof(ObjDictMaster_Index5FFF[0]), 0x5FFF},
};

const indextable * ObjDictMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1016: i = 2;break;
		case 0x1017: i = 3;*callbacks = ObjDictMaster_Index1017_callbacks; break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1600: i = 8;break;
		case 0x5FFF: i = 9;*callbacks = IAP_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDictMaster_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDictMaster_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index ObjDictMaster_firstIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index ObjDictMaster_lastIndex = {
  5, /* SDO_SVR */
  6, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 ObjDictMaster_ObjdictSize = sizeof(ObjDictMaster_objdict)/sizeof(ObjDictMaster_objdict[0]); 

CO_Data ObjDictMaster_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDictMaster);

